/*
 * This file is generated by jOOQ.
 */
package gim.mysql.jooq.model.test.tables.records;


import gim.mysql.jooq.model.test.tables.Member;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 회원 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.member.member_id</code>. 회원 아이디
     */
    public void setMemberId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.member.member_id</code>. 회원 아이디
     */
    public UInteger getMemberId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>test.member.member_name</code>. 회원 이름
     */
    public void setMemberName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.member.member_name</code>. 회원 이름
     */
    public String getMemberName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.member.member_active</code>. 회원 활성화 여부
     */
    public void setMemberActive(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.member.member_active</code>. 회원 활성화 여부
     */
    public String getMemberActive() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.member.created_time</code>. 등록시간
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.member.created_time</code>. 등록시간
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>test.member.updated_time</code>. 수정시간
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.member.updated_time</code>. 수정시간
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(UInteger memberId, String memberName, String memberActive, LocalDateTime createdTime, LocalDateTime updatedTime) {
        super(Member.MEMBER);

        setMemberId(memberId);
        setMemberName(memberName);
        setMemberActive(memberActive);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        resetChangedOnNotNull();
    }
}
