/*
 * This file is generated by jOOQ.
 */
package gim.mysql.jooq.model.test;


import gim.mysql.jooq.model.test.tables.Member;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 회원 테이블
     */
    public static final Member MEMBER = Member.MEMBER;
}
